[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31"
tokio = { version = "1", features = ["full"] }
backend = { path = "../backend" }
frontend = { path = "../frontend" }